name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set version in build.gradle.kts
      run: |
        VERSION=${GITHUB_REF#refs/tags/v}
        sed -i "s/version = \".*\"/version = \"$VERSION\"/" build.gradle.kts

    - name: Build with Gradle
      run: ./gradlew buildPlugin

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Create Release and Upload Asset
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.VERSION }}
        files: ./build/libs/idea-plugin-dependency-folding-${{ steps.get_version.outputs.VERSION }}.jar
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
